<?php

namespace App\Repository\Eloquent;

use App\Models\Financial;
use Illuminate\Database\Eloquent\Model;

/**
 *
 */
class FinancialRepository extends BaseRepository
{

    /**
     * @param Financial $financial
     */
    public function __construct(Financial $financial)
    {
        parent::__construct($financial);
    }

    /**
     * @param array $attributes
     * @return Model
     */
    public function create(array $attributes): Model
    {
        return parent::create($attributes); // TODO: Change the autogenerated stub
    }
}
