<?php

namespace App\Repository\Eloquent;

use App\Models\LocalVision;
use Illuminate\Database\Eloquent\Collection;

/**
 *
 */
class LocalVisionRepository extends BaseRepository
{

    /**
     * @param LocalVision $localVision
     */
    public function __construct(LocalVision $localVision)
    {
        parent::__construct($localVision);
    }

    /**
     * @param int $projectId
     * @return Collection
     */
    public function getAllLocalVisionsByProjectId(int $projectId): Collection
    {
        /** @var Collection|null $collection */

        return LocalVision::where('project_id', '=', $projectId)->orderBy('accepted', 'ASC')
            ->orderBy('created_at', 'DESC')->with('author')->get(); // TODO: Change the autogenerated stub
    }
}
