<?php

namespace App\Repository\Eloquent;

use App\Models\TechnicalDetails;
use Illuminate\Database\Eloquent\Model;

/**
 *
 */
class TechnicalDetailsRepository extends BaseRepository
{

    /**
     * @param TechnicalDetails $technicalDetails
     */
    public function __construct(TechnicalDetails $technicalDetails)
    {
        parent::__construct($technicalDetails);
    }

    /**
     * @param array $attributes
     * @return Model
     */
    public function create(array $attributes): Model
    {
        return parent::create($attributes); // TODO: Change the autogenerated stub
    }
}
