<?php

namespace App\Repository\Eloquent;

use App\Models\User;
use Illuminate\Database\Eloquent\Model;

/**
 *
 */
class UserRepository extends BaseRepository
{

    /**
     * @param User $user
     */
    public function __construct(User $user)
    {
        parent::__construct($user);
    }

    /**
     * @param array $attributes
     * @return Model
     */
    public function create(array $attributes): Model
    {
        return parent::create($attributes); // TODO: Change the autogenerated stub
    }

    /**
     *
     */
    public function search()
    {

    }

}
