version: '3.7'

services:
  database:
    container_name: db_dbr77
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: database
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
    ports:
      - '3306:3306'
  php:
    container_name: php_dbr77
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    ports:
      - 9000:9000
    volumes:
      - ./:/var/www
    depends_on:
      - database
  nginx:
    container_name: nginx_dbr77
    image: nginx:stable-alpine
    ports:
      - '80:80'
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/log:/var/log/nginx
    depends_on:
      - php
      - database
